#!/bin/bash

# Build a universal binary of the application
cd AppTrap
xcodebuild -configuration Release -nodependencies clean # Start fresh
xcodebuild -configuration Release

# Build a universal binary of the prefpane
cd ../AppTrapPreferencePane
xcodebuild -configuration Release -nodependencies clean # Start fresh
xcodebuild -configuration Release

echo "Copying files..."
cd ..
# Make a copy of the prefpane
cp -Rf AppTrapPreferencePane/build/Release/AppTrap.prefPane AppTrap.prefPane
# Copy application into prefpane bundle
cp -Rf AppTrap/build/Release/AppTrap.app AppTrap.prefPane/Contents/Resources

echo "Creating disk image..."
# Create a new dmg from the template
cp AppTrap_template.dmg AppTrap_tmp.dmg

# Mount the new dmg
hdiutil attach AppTrap_tmp.dmg

# Copy the application to the new dmg
rsync --recursive --delete AppTrap.prefPane /Volumes/AppTrap

# Detach the new dmg
hdiutil detach /Volumes/AppTrap

# Convert the new dmg to compressed format
rm AppTrap.dmg
hdiutil convert AppTrap_tmp.dmg -format UDBZ -o AppTrap.dmg

# Clean up
rm AppTrap_tmp.dmg
rm -R AppTrap.prefPane

echo "Done!"
